// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc6xmcaKQqJ7hmTUImyantddlgNaQUOJo',
    appId: '1:252799961958:web:5fca31842f352552e1d6a7',
    messagingSenderId: '252799961958',
    projectId: 'cruud-b06af',
    authDomain: 'cruud-b06af.firebaseapp.com',
    databaseURL: 'https://cruud-b06af-default-rtdb.firebaseio.com',
    storageBucket: 'cruud-b06af.appspot.com',
    measurementId: 'G-4FE8WVRL8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0m0MqnvayOf3Jwym5pVnFBAf1NcMv8bg',
    appId: '1:252799961958:android:f34510928d1dba37e1d6a7',
    messagingSenderId: '252799961958',
    projectId: 'cruud-b06af',
    databaseURL: 'https://cruud-b06af-default-rtdb.firebaseio.com',
    storageBucket: 'cruud-b06af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHRC9jFVx7eaepkqYEo0Ig5EbnqS0CZoQ',
    appId: '1:252799961958:ios:d03181ef5d8939e8e1d6a7',
    messagingSenderId: '252799961958',
    projectId: 'cruud-b06af',
    databaseURL: 'https://cruud-b06af-default-rtdb.firebaseio.com',
    storageBucket: 'cruud-b06af.appspot.com',
    iosClientId: '252799961958-si33t4dcl8uj972nturtckgqmpt7vla4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bajuloNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHRC9jFVx7eaepkqYEo0Ig5EbnqS0CZoQ',
    appId: '1:252799961958:ios:d03181ef5d8939e8e1d6a7',
    messagingSenderId: '252799961958',
    projectId: 'cruud-b06af',
    databaseURL: 'https://cruud-b06af-default-rtdb.firebaseio.com',
    storageBucket: 'cruud-b06af.appspot.com',
    iosClientId: '252799961958-si33t4dcl8uj972nturtckgqmpt7vla4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bajuloNew',
  );
}
